householdPower <- read.delim('./household_power_consumption.txt', sep = ";")
householdPower$Date <-  dmy(householdPower$Date)
householdPower$Time <- hms(householdPower$Time)
myDay1 <- ymd("2007-02-01")
myDay2 <- ymd("2007-02-02")
powerDays <- subset(householdPower, Date == myDay1 | Date == myDay2)
powerDays$Global_active_power<- as.numeric(as.character(powerDays$Global_active_power))
timeSeconds <- seconds_to_period(powerDays$Time)
timeSeconds <- sprintf('%02d:%02d:%02d', timeSeconds@hour, minute(timeSeconds), second(timeSeconds))
powerDays$dateTime <- ymd_hms(paste(powerDays$Date,timeSeconds))
png(file = "plot3.png")
with(subset(powerDays), plot(dateTime, Sub_metering_1, type = "n", xlab = "", ylab = "energy sub metering"))
with(subset(powerDays), points(dateTime, Sub_metering_1, type = "l"))
with(subset(powerDays), points(dateTime, Sub_metering_2, type = "l", col = "red"))
with(subset(powerDays), points(dateTime, Sub_metering_3, type = "l", col = "blue"))
legend("topright", legend = c("sub_metering_1","sub_metering_2","sub_metering_3"), col = c("black","red","blue"), lty = 1, bty = "n")
dev.off()