householdPower <- read.delim('./household_power_consumption.txt', sep = ";")
householdPower$Date <-  dmy(householdPower$Date)
householdPower$Time <- hms(householdPower$Time)
myDay1 <- ymd("2007-02-01")
myDay2 <- ymd("2007-02-02")
powerDays <- subset(householdPower, Date == myDay1 | Date == myDay2)
powerDays$Global_active_power<- as.numeric(as.character(powerDays$Global_active_power))
timeSeconds <- seconds_to_period(powerDays$Time)
timeSeconds <- sprintf('%02d:%02d:%02d', timeSeconds@hour, minute(timeSeconds), second(timeSeconds))
powerDays$dateTime <- ymd_hms(paste(powerDays$Date,timeSeconds))
png(file = "plot2.png")
with(powerDays, plot(Global_active_power ~ dateTime, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)"))
dev.off()